/**
 * @fileoverview Codigos de error del modulo Solicitud de Distribuidora.
 *
 * Concentra las constantes para que cualquier modulo refiera los
 * mismos errores y los mensajes no diverjan. Sigue el estandar
 * `{MODULO}.{ACCION}` del envelope de respuesta del proyecto
 * (`docs/backend/estilos/respuestas-api.md`).
 *
 * @module distribuidores
 * @author Equipo de desarrollo Mis Vales
 * @since 2.1.0
 */

export const SOLICITUD_ERROR_CODES = {
  NOT_FOUND: 'DISTRIBUIDOR.SOLICITUD.NOT_FOUND',
  NOT_IN_VERIFICATION: 'DISTRIBUIDOR.SOLICITUD.NOT_IN_VERIFICATION',
  NOT_DICTAMINATED: 'DISTRIBUIDOR.SOLICITUD.NOT_DICTAMINADA',
  NOT_OPEN: 'DISTRIBUIDOR.SOLICITUD.NOT_OPEN',
  NOT_EDITABLE: 'DISTRIBUIDOR.SOLICITUD.NOT_EDITABLE',
  VALIDATION: 'DISTRIBUIDOR.SOLICITUD.VALIDATION',
  COORDINATOR_NO_BRANCH: 'DISTRIBUIDOR.SOLICITUD.COORDINATOR_NO_BRANCH',
  VERIFIER_NO_BRANCH: 'DISTRIBUIDOR.SOLICITUD.VERIFIER_NO_BRANCH',
  ACTOR_NOT_BRANCH_MANAGER: 'DISTRIBUIDOR.SOLICITUD.ACTOR_NOT_BRANCH_MANAGER',
  MODIFICATION_REQUIRES_AUTH:
    'DISTRIBUIDOR.SOLICITUD.MODIFICATION_REQUIRES_AUTH',
  LIMIT_CREDIT_REQUIRED: 'DISTRIBUIDOR.SOLICITUD.LIMIT_CREDIT_REQUIRED',
  ALREADY_OPEN: 'DISTRIBUIDOR.SOLICITUD.ALREADY_OPEN',
  EMAIL_ALREADY_EXISTS: 'DISTRIBUIDOR.SOLICITUD.EMAIL_ALREADY_EXISTS',
  CURP_ALREADY_EXISTS: 'DISTRIBUIDOR.SOLICITUD.CURP_ALREADY_EXISTS',
  RFC_ALREADY_EXISTS: 'DISTRIBUIDOR.SOLICITUD.RFC_ALREADY_EXISTS',
  INE_DOCUMENT_NOT_FOUND: 'DISTRIBUIDOR.SOLICITUD.INE_DOCUMENT_NOT_FOUND',
} as const;
